name: Workflow
on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    name: Build Application and Deploy Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker-compose up --abort-on-container-exit # Stop all services on finish
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
            repo_token: "${{secrets.GITHUB_TOKEN}}"
            prerelease: false
            automatic_release_tag: "latest"
            files: |
              ./target/*.jar
  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Integration Tests
        run: |
          docker build -t database ./db 
          docker run --name world -dp 33060:3306 database
          mvn -Dtest=com.napier.Ambry.AmbryTest test
          docker stop world
          docker rm world
          docker image rm database
      - name: CodeCov
        uses: codecov/codecov-action@v4.3.0
        with:
          fail_ci_if_error: false # optional (default = false)
          directory: ./target/site/jacoco/ # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true # optional (default = false)
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Unit Tests
        run: |
          mvn package -DskipTests
          mvn -Dtest=com.napier.Ambry.AmbryTest test -e
      - name: CodeCov
        uses: codecov/codecov-action@v4.3.0
        with:
          fail_ci_if_error: false # optional (default = false)
          directory: ./target/site/jacoco/ # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true # optional (default = false)