name: Test Workflow
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup network
        run: |
          docker network create --driver bridge Ambry-b+Bridge
          docker pull mongo
          docker run -d --name mongo-dbserver --network Ambry-Bridge mongo
      - name: Build with Maven
        run: mvn package
      - name: Build
        run: docker build -t Ambry_Docker .
      - name: Run image
        run: docker run --network Ambry-Bridge --name Ambry_Container Ambry_Docker
      - name: view logs
        run: docker logs Ambry_Container
