name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup network
        run: |
          docker network create --driver bridge ambry-bridge
          docker pull mongo
          docker run -d --name mongo-dbserver --network ambry-bridge mongo
      - name: Build with Maven
        run: mvn package
      - name: Build
        run: docker build -t ambry .
      - name: Run image
        run: docker run --network ambry-bridge --name ambrycontainer ambry
      - name: view logs
        run: docker logs ambrycontainer
